# version: "3.8"

services:

    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html/wordpress
            - ./requirements/bonus/website/tools:/var/www/html/static
        depends_on:
            - wordpress
        networks:
            - inception

    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        restart: always
        expose:
            - "9000"
        volumes:
            - wordpress:/var/www/html/wordpress
        environment:
            - WP_ADM=${WP_ADM}
            - WP_ADM_PASSWORD=${WP_ADM_PASSWORD}
            - WP_ADM_EMAIL=${WP_ADM_EMAIL}
            - WP_USER=${WP_USER}
            - WP_USER_PASSWORD=${WP_USER_PASSWORD}
            - WP_USER_EMAIL=${WP_USER_EMAIL}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_USER_PASSWORD=${DB_USER_PASSWORD}
            - WP_REDIS_HOST=redis
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - inception

    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_USER_PASSWORD=${DB_USER_PASSWORD}
            - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - inception

# bonuses
    adminer:
        build: ./requirements/bonus/adminer/
        container_name: adminer
        restart: always
        ports:
            - "700:80"
        depends_on:
            - mariadb
        networks:
            - inception

    ftp:
        build: ./requirements/bonus/ftp/
        container_name: ftp
        restart: always
        ports:
            - "21:21"
            - "10000-10010:10000-10010"
        volumes:
            - wordpress:/var/www/html/wordpress
        environment:
            - FTP_USER=${FTP_USER}
            - FTP_PASSWORD=${FTP_PASSWORD}
        networks:
            - inception

    netdata:
        build: ./requirements/bonus/netdata/
        container_name: netdata
        restart: always
        ports:
            - "19999:19999"
        volumes:
            - netdata_config:/etc/netdata
            - netdata_lib:/var/lib/netdata
            - netdata_cache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro

    redis:
        build: ./requirements/bonus/redis/
        container_name: redis
        restart: always
        expose:
            - "6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - inception
# end of bonuses

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/akurochk/data/wordpress
    db:
        name: db
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/akurochk/data/mariadb
# bonuses
    netdata_config:
    netdata_lib:
    netdata_cache:
# end of bonuses

networks:
    inception:
        name: inception
